language: python

sudo: false

cache: pip

python:
   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"

env:
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
  - DJANGO='django>=2.1,<2.2'
  - DJANGO='django>=2.0,<2.1'
  - DJANGO='django>=1.11,<1.12'

install:
  - travis_retry pip install --upgrade pip setuptools wheel
  - travis_retry pip install --upgrade $DJANGO
  - travis_retry pip install --upgrade -r requirements.txt

script:
  - coverage run --source herald runtests.py -v 2

notifications:
  email: false

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: DJANGO='django>=2.1,<2.2'
    - python: 3.7
      dist: xenial
      sudo: true
      env: DJANGO='django>=2.0,<2.1'
    - python: 3.7
      dist: xenial
      sudo: true
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
      
  exclude:
    - python: "2.7"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "2.7"
      env: DJANGO='django>=2.0,<2.1'
    - python: "2.7"
      env: DJANGO='django>=2.1,<2.2'
    - python: "3.4"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.4"
      env: DJANGO='django>=2.1,<2.2'
    - python: "3.7"
      env: DJANGO='django>=1.11,<1.12'

  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
  fast_finish: true

after_success:
    - coveralls
